/* Generated By:JJTree: Do not edit this line. ASTAttributeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

import java.util.*;

public
class ASTAttributeList extends SimpleNode {

  String name;
  Vector lst = new Vector();


  public ASTAttributeList(int id) {
    super(id);
  }

  public ASTAttributeList(bonXaiTree p, int id) {
    super(p, id);
  }


    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


  public void setList(Vector lst){
   this.lst=lst;

  }


  public List getList(){
    return lst;
  }




  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8a2000373a1e41b0a218f631b78116d1 (do not edit this line) */
