/* Generated By:JJTree: Do not edit this line. ASTAttrBonxaiType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTAttrBonxaiType extends SimpleNode {

  String name;
  String type;
  Boolean fixed;
  Boolean def;

  public ASTAttrBonxaiType(int id) {
    super(id);
  }

  public ASTAttrBonxaiType(bonXaiTree p, int id) {
    super(p, id);
  }



    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


    public void setType(String type){
    this.type = type;
  }


  public String getType(){
    return type;
  }



    public void setFixed(Boolean fixed) {
    this.fixed = fixed;
  }


  public Boolean getFixed(){
    return fixed;
  }


    public void setDefault(Boolean def) {
    this.def = def;
  }


  public Boolean getDeafult(){
    return def;
  }




  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d606dbaeda02c73f3d925e672de56eae (do not edit this line) */
