/* Generated By:JJTree: Do not edit this line. ASTConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

import java.util.HashSet;

public class ASTConstraint extends SimpleNode {

    private String selector;
    private HashSet<String> fields;

  public ASTConstraint(int id) {
    super(id);
  }

  public ASTConstraint(bonXaiTree p, int id) {
    super(p, id);
  }

  public void setSelector(String selector){
    this.selector = selector;
  }

  public String getSelector(){
    return selector;
  }

  public void setFields(HashSet<String> fields){
    this.fields = fields;
  }

  public HashSet<String> getFields(){
    return fields;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1e072a9cd5c965c60faf5557db3ba14f (do not edit this line) */
