/* Generated By:JJTree: Do not edit this line. ASTConstraintBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTConstraintBlock extends SimpleNode {
  public ASTConstraintBlock(int id) {
    super(id);
  }

  public ASTConstraintBlock(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c89b12cfab2036ed8ef9484c013f4183 (do not edit this line) */
