/* Generated By:JJTree: Do not edit this line. ASTElementPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTElementPattern extends SimpleNode {

  Boolean empty;
  Boolean missing;

  public ASTElementPattern(int id) {
    super(id);
  }

  public ASTElementPattern(bonXaiTree p, int id) {
    super(p, id);
  }

    public void setEmpty(Boolean empty) {
    this.empty = empty;
  }


  public Boolean getEmpty(){
    return empty;
  }


    public void setMissing(Boolean missing) {
    this.missing = missing;
  }


  public Boolean getMissing(){
    return missing;
  }




  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbd0700f85c0179bbdba4a20e466bc69 (do not edit this line) */
