/* Generated By:JJTree: Do not edit this line. ASTForeign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTForeign extends SimpleNode {
  public ASTForeign(int id) {
    super(id);
  }

  public ASTForeign(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d8290a545a6397aecfe0118b02803b3d (do not edit this line) */
