/* Generated By:JJTree: Do not edit this line. ASThost.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASThost extends SimpleNode {
  public ASThost(int id) {
    super(id);
  }

  public ASThost(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ae62b0980ce1a4810349fbd79ac75b8 (do not edit this line) */
