/* Generated By:JJTree: Do not edit this line. ASTKeyRefConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTKeyRefConstraint extends ASTConstraint {

  String name;

  public ASTKeyRefConstraint(int id) {
    super(id);
  }

  public ASTKeyRefConstraint(bonXaiTree p, int id) {
    super(p, id);
  }

  public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d7624597b797735a1e8a012f4e86d16 (do not edit this line) */
