/* Generated By:JJTree: Do not edit this line. ASTNamespaceUriLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;

public
class ASTNamespaceUriLiteral extends SimpleNode {
  public ASTNamespaceUriLiteral(int id) {
    super(id);
  }

  public ASTNamespaceUriLiteral(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5c8fb8ca8b466043494f40170ca5e10 (do not edit this line) */
