/* Generated By:JJTree: Do not edit this line. ASTQuotationName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;


public
class ASTQuotationName extends SimpleNode {
  public ASTQuotationName(int id) {
    super(id);
  }

  public ASTQuotationName(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b4f8a86bc81dd5e97d855da90bc6082c (do not edit this line) */
