/* Generated By:JJTree: Do not edit this line. ASTRegex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;


public
class ASTRegex extends SimpleNode {

  int numberBefore;
  int numberAfter;
  boolean concatenation;
  boolean disjunction;
  String  operator;
  String  secondoperator;


  public boolean isConcatenation() {
	  return concatenation;
  }

  public void setConcatenation(boolean concatenation) {
	  this.concatenation = concatenation;
  }

  public boolean isDisjunction() {
	  return disjunction;
  }

  public void setDisjunction(boolean disjunction) {
	  this.disjunction = disjunction;
  }

  public ASTRegex(int id) {
    super(id);
  }

  public ASTRegex(bonXaiTree p, int id) {
    super(p, id);
  }

    public void setNumberBefore(Integer number){
    this.numberBefore = number;
  }


  public Integer getNumberBefore(){
    return numberBefore ;
  }


    public void setNumberAfter(Integer number){
    this.numberAfter = number;
  }


  public Integer getNumberAfter(){
    return numberAfter;
  }


    public void setOperator(String operator){
    this.operator = operator;
  }


  public String getOperator(){
    return operator;
  }

    public void setSecondOperator(String secondoperator){
    this.secondoperator = secondoperator;
  }


  public String getSecondOperator(){
    return secondoperator;
  }




  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e87050f44783fb358184e8f55c50fb1 (do not edit this line) */
