/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package de.tudortmund.cs.bonxai.bonxai.parser;


public
class ASTType extends SimpleNode {

  String name;
  String type;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(bonXaiTree p, int id) {
    super(p, id);
  }


  public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }

    public void setType(String type){
    this.type = type;
  }


  public String getType(){
    return type;
  }




  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c09e9cc9fbedb193fd948b503b2321ba (do not edit this line) */
