/* Generated By:JJTree: Do not edit this line. ./bonXaiTreeTreeConstants.java */

package de.tudortmund.cs.bonxai.bonxai.parser;

public interface bonXaiTreeTreeConstants
{
  public int JJTBONXAI = 0;
  public int JJTDECL = 1;
  public int JJTVOID = 2;
  public int JJTCONSTRAINTBLOCK = 3;
  public int JJTCONSTRAINT = 4;
  public int JJTUNIQUECONSTRAINT = 5;
  public int JJTKEYCONSTRAINT = 6;
  public int JJTKEYREFCONSTRAINT = 7;
  public int JJTCONSTRAINTSELECTOR = 8;
  public int JJTCONSTRAINTFIELDS = 9;
  public int JJTGROUPBLOCK = 10;
  public int JJTGROUPRULE = 11;
  public int JJTBLOCK = 12;
  public int JJTROOTELEMENTS = 13;
  public int JJTEXPR = 14;
  public int JJTANNOTATIONS = 15;
  public int JJTANNOTATION = 16;
  public int JJTANNOTATIONNAME = 17;
  public int JJTANNOTATIONVALUE = 18;
  public int JJTAPATTERN = 19;
  public int JJTSIMPLEAPATTERN = 20;
  public int JJTSIMPLEAPATTERNOR = 21;
  public int JJTFULLAPATTERN = 22;
  public int JJTFULLAPATTERNOR = 23;
  public int JJTCPATTERN = 24;
  public int JJTELEMENTPATTERN = 25;
  public int JJTMIXEDREGEX = 26;
  public int JJTALL = 27;
  public int JJTREGEX = 28;
  public int JJTNAMEDTYPE = 29;
  public int JJTATTRIBUTEPATTERN = 30;
  public int JJTATTRIBUTELIST = 31;
  public int JJTNAMESPACELIST = 32;
  public int JJTFOREIGN = 33;
  public int JJTBONXAITYPE = 34;
  public int JJTATTRBONXAITYPE = 35;


  public String[] jjtNodeName = {
    "bonXai",
    "Decl",
    "void",
    "ConstraintBlock",
    "Constraint",
    "UniqueConstraint",
    "KeyConstraint",
    "KeyRefConstraint",
    "ConstraintSelector",
    "ConstraintFields",
    "GroupBlock",
    "GroupRule",
    "Block",
    "RootElements",
    "Expr",
    "Annotations",
    "Annotation",
    "AnnotationName",
    "AnnotationValue",
    "APattern",
    "SimpleAPattern",
    "SimpleAPatternOr",
    "FullAPattern",
    "FullAPatternOr",
    "CPattern",
    "ElementPattern",
    "MixedRegex",
    "All",
    "Regex",
    "NamedType",
    "AttributePattern",
    "AttributeList",
    "NameSpaceList",
    "Foreign",
    "BonxaiType",
    "AttrBonxaiType",
  };
}
