/* Generated By:JavaCC: Do not edit this line. BonxaiJJParserConstants.java */
package eu.fox7.schematoolkit.bonxai.parser;

public interface BonxaiJJParserConstants {

  int EOF = 0;
  int QUOTE = 5;
  int SINGLE_LINE_COMMENT = 6;
  int GLOBAL = 7;
  int GRAMMAR = 8;
  int TARGET_NAMESPACE = 9;
  int NAMESPACE = 10;
  int TYPE = 11;
  int DEFAULTT = 12;
  int DATATYPES = 13;
  int IMPORT = 14;
  int CONSTRAINTS = 15;
  int UNIQUE = 16;
  int KEY = 17;
  int KEYREF = 18;
  int GROUPS = 19;
  int GROUP = 20;
  int ATTRIBUTEGROUP = 21;
  int ATTRIBUTEREF = 22;
  int ATTRIBUTE = 23;
  int MIXED = 24;
  int EMPTY = 25;
  int NILLABLE = 26;
  int ELEMENTREF = 27;
  int ELEMENT = 28;
  int STRICT = 29;
  int LAX = 30;
  int SKIPP = 31;
  int FIXED = 32;
  int ANY = 33;
  int ANYATTRIBUTE = 34;
  int NOT = 35;
  int NAMEX = 36;
  int CONSTANT = 37;
  int OPENING_ROUND_BRACKET = 38;
  int CLOSING_ROUND_BRACKET = 39;
  int OPENING_SQUARED_BRACKET = 40;
  int CLOSING_SQUARED_BRACKET = 41;
  int OPENING_CURLY_BRACKET = 42;
  int CLOSING_CURLY_BRACKET = 43;
  int EQUALS = 44;
  int COMMA = 45;
  int AT = 46;
  int OR = 47;
  int ANDLITERAL = 48;
  int DOUBLESLASH = 49;
  int SLASH = 50;
  int STAR = 51;
  int PLUS = 52;
  int QUESTION_MARK = 53;
  int COLON = 54;
  int POINT = 55;
  int PERCENT = 56;
  int ANNOTATION_VALUE = 57;
  int DIGIT = 58;
  int BASECHAR = 59;
  int IDEOGRAPHIC = 60;
  int COMBINING_CHAR = 61;
  int EXTENDER = 62;
  int LABEL = 63;
  int PROTOCOL = 64;
  int URI = 65;
  int QUOTATION = 66;
  int QUOT_QUOTE = 67;

  int DEFAULT = 0;
  int NAME = 1;
  int URIX = 2;
  int QUOTATIONX = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\"\"",
    "<SINGLE_LINE_COMMENT>",
    "\"global\"",
    "\"grammar\"",
    "\"target namespace\"",
    "\"namespace\"",
    "\"type\"",
    "\"default\"",
    "\"datatypes \"",
    "\"import\"",
    "\"constraints\"",
    "\"unique\"",
    "\"key\"",
    "\"keyref \"",
    "\"groups\"",
    "\"group\"",
    "\"attribute-group\"",
    "\"attributeref\"",
    "\"attribute\"",
    "\"mixed\"",
    "\"empty\"",
    "\"nillable\"",
    "\"elementref\"",
    "\"element\"",
    "\"strict\"",
    "\"lax\"",
    "\"skip\"",
    "\"fixed\"",
    "\"any\"",
    "\"anyattribute\"",
    "\"not\"",
    "\"name\"",
    "<CONSTANT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\"@\"",
    "\"|\"",
    "\"&\"",
    "\"//\"",
    "\"/\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\":\"",
    "\".\"",
    "\"%\"",
    "\"annotation\"",
    "<DIGIT>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<COMBINING_CHAR>",
    "<EXTENDER>",
    "<LABEL>",
    "<PROTOCOL>",
    "<URI>",
    "<QUOTATION>",
    "\"\\\"\"",
  };

}
