/* Generated By:JavaCC: Do not edit this line. BonxaiJJParserConstants.java */
package eu.fox7.schematoolkit.bonxai.parser;

public interface BonxaiJJParserConstants {

  int EOF = 0;
  int QUOTE = 5;
  int SINGLE_LINE_COMMENT = 6;
  int ROOTS = 7;
  int GRAMMAR = 8;
  int DEFAULT_NAMESPACE = 9;
  int NAMESPACE = 10;
  int TYPE = 11;
  int DEFAULTT = 12;
  int DATATYPES = 13;
  int IMPORT = 14;
  int CONSTRAINTS = 15;
  int UNIQUE = 16;
  int KEY = 17;
  int KEYREF = 18;
  int GROUPS = 19;
  int GROUP = 20;
  int ATTRIBUTEGROUP = 21;
  int ATTRIBUTE = 22;
  int MIXED = 23;
  int EMPTY = 24;
  int MISSING = 25;
  int ELEMENT = 26;
  int STRICT = 27;
  int LAX = 28;
  int SKIPP = 29;
  int FIXED = 30;
  int CONSTANT = 31;
  int OPENING_ROUND_BRACKET = 32;
  int CLOSING_ROUND_BRACKET = 33;
  int OPENING_SQUARED_BRACKET = 34;
  int CLOSING_SQUARED_BRACKET = 35;
  int OPENING_CURLY_BRACKET = 36;
  int CLOSING_CURLY_BRACKET = 37;
  int EQUALS = 38;
  int COMMA = 39;
  int AT = 40;
  int OR = 41;
  int ANDLITERAL = 42;
  int DOUBLESLASH = 43;
  int SLASH = 44;
  int STAR = 45;
  int PLUS = 46;
  int QUESTION_MARK = 47;
  int COLON = 48;
  int POINT = 49;
  int ANNOTATION_VALUE = 50;
  int DIGIT = 51;
  int BASECHAR = 52;
  int IDEOGRAPHIC = 53;
  int COMBINING_CHAR = 54;
  int EXTENDER = 55;
  int LABEL = 56;
  int PROTOCOL = 57;
  int URI = 58;
  int QUOTATION = 59;
  int QUOT_QUOTE = 60;

  int DEFAULT = 0;
  int NAME = 1;
  int URIX = 2;
  int QUOTATIONX = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\"\"",
    "<SINGLE_LINE_COMMENT>",
    "\"roots\"",
    "\"grammar\"",
    "\"default namespace\"",
    "\"namespace\"",
    "\"type\"",
    "\"default\"",
    "\"datatypes \"",
    "\"import\"",
    "\"constraints\"",
    "\"unique\"",
    "\"key\"",
    "\"keyref \"",
    "\"groups\"",
    "\"group\"",
    "\"attribute-group\"",
    "\"attribute\"",
    "\"mixed\"",
    "\"empty\"",
    "\"missing\"",
    "\"element\"",
    "\"strict\"",
    "\"lax\"",
    "\"skip\"",
    "\"fixed\"",
    "<CONSTANT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\"@\"",
    "\"|\"",
    "\"&\"",
    "\"//\"",
    "\"/\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\":\"",
    "\".\"",
    "\"annotation\"",
    "<DIGIT>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<COMBINING_CHAR>",
    "<EXTENDER>",
    "<LABEL>",
    "<PROTOCOL>",
    "<URI>",
    "<QUOTATION>",
    "\"\\\"\"",
  };

}
