/* Generated By:JJTree: Do not edit this line. ASTAnnotations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTAnnotations extends SimpleNode {
  public ASTAnnotations(int id) {
    super(id);
  }

  public ASTAnnotations(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=22c5045a47c0a56db7b62d95c81e3fbc (do not edit this line) */
