package eu.fox7.bonxai.bonxai.parser;
/* Generated By:JJTree: Do not edit this line. ASTAnnotationValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnnotationValue extends SimpleNode {

  String name;

  public ASTAnnotationValue(int id) {
    super(id);
  }

  public ASTAnnotationValue(bonXaiTree p, int id) {
    super(p, id);
  }



    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bea3517e9e6bc4e072353762dc5f6b6c (do not edit this line) */
