/* Generated By:JJTree: Do not edit this line. ASTAttributePattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

import java.util.*;

public
class ASTAttributePattern extends SimpleNode {


  Vector namespaceLst = new Vector();
  Vector attributeLst = new Vector();
  String foreign;

  public ASTAttributePattern(int id) {
    super(id);
  }

  public ASTAttributePattern(bonXaiTree p, int id) {
    super(p, id);
  }


 public void setForeign(String foreign){
    this.foreign = foreign;
  }


  public String getForeign(){
    return foreign;
  }


  public void setAttributeList(Vector lst){
   this.attributeLst=lst;

  }


  public List getAttributeList(){
    return attributeLst;
  }


  public void setNamespaceList(Vector lst){
   this.namespaceLst=lst;

  }


  public List getNamespaceList(){
    return namespaceLst;
  }



  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d9d7ef1d89c456ceac4b431682ca0b64 (do not edit this line) */
