/* Generated By:JJTree: Do not edit this line. ASTAPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTAPattern extends SimpleNode {
  public ASTAPattern(int id) {
    super(id);
  }

  public ASTAPattern(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=abf312dbf20ebbc4c35e2a7fa9ae1591 (do not edit this line) */
