/* Generated By:JJTree: Do not edit this line. ASTConstraintSelector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package eu.fox7.bonxai.bonxai.parser;

public
class ASTConstraintSelector extends SimpleNode {
  public ASTConstraintSelector(int id) {
    super(id);
  }

  public ASTConstraintSelector(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a1222253e0d657cb3eaabea24b572f9 (do not edit this line) */
