/* Generated By:JJTree: Do not edit this line. ASTCPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package eu.fox7.bonxai.bonxai.parser;

public
class ASTCPattern extends SimpleNode {
  public ASTCPattern(int id) {
    super(id);
  }

  public ASTCPattern(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=22e77e25006e05f3d92b89b17b88169e (do not edit this line) */
