/* Generated By:JJTree: Do not edit this line. ASTDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTDecl extends SimpleNode {

private String uri;
private String ident;
private String url="";


  public ASTDecl(int id) {
    super(id);
  }

  public ASTDecl(bonXaiTree p, int id) {
    super(p, id);
  }


 public void setUri(String uri) {
        this.uri = uri;
    }
  public String getUri() {
        return uri;
    }

 public void setIdentifier(String ident) {
        this.ident = ident;
    }
  public String getIdentifier() {
        return ident;
    }

 public void setUrl(String url) {
        this.url = url;
    }
  public String getUrl() {
        return url;
    }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b0bcbc8f26e58321cda78f66dc491e1 (do not edit this line) */
