/* Generated By:JJTree: Do not edit this line. ASTFullAPatternOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package eu.fox7.bonxai.bonxai.parser;

public
class ASTFullAPatternOr extends SimpleNode {
  public ASTFullAPatternOr(int id) {
    super(id);
  }

  public ASTFullAPatternOr(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8366e2781b09c7832f257d76a36409cd (do not edit this line) */
