/* Generated By:JJTree: Do not edit this line. ASTGroupRule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTGroupRule extends SimpleNode {

 String name;

  public ASTGroupRule(int id) {
    super(id);
  }

  public ASTGroupRule(bonXaiTree p, int id) {
    super(p, id);
  }

    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=af862c12d376f6b6088aa80ea9016970 (do not edit this line) */
