/* Generated By:JJTree: Do not edit this line. ASTKeyConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTKeyConstraint extends ASTConstraint {

  String name;

  public ASTKeyConstraint(int id) {
    super(id);
  }

  public ASTKeyConstraint(bonXaiTree p, int id) {
    super(p, id);
  }

    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b3edb7e0a8e368b493d4441f5a36661 (do not edit this line) */
