/* Generated By:JJTree: Do not edit this line. ASTMixedRegex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTMixedRegex extends SimpleNode {
  public ASTMixedRegex(int id) {
    super(id);
  }

  public ASTMixedRegex(bonXaiTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=110124675e53474bc77b378c4ab762d5 (do not edit this line) */
