/* Generated By:JJTree: Do not edit this line. ASTNamedType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

import java.util.*;

public
class ASTNamedType extends SimpleNode {

  String name;
  String foreign;
  Integer numberBefore;
  Integer numberAfter;
  Vector lst = new Vector();


  public ASTNamedType(int id) {
    super(id);
  }

  public ASTNamedType(bonXaiTree p, int id) {
    super(p, id);
  }

    public void setName(String name){
    this.name = name;
  }


  public String getName(){
    return name;
  }

    public void setForeign(String foreign){
    this.foreign = foreign;
  }


  public String getForeign(){
    return foreign;
  }


    public void setNumberBefore(Integer number){
    this.numberBefore = number;
  }


  public Integer getNumberBefore(){
    return numberBefore ;
  }


    public void setNumberAfter(Integer number){
    this.numberAfter = number;
  }


  public Integer getNumberAfter(){
    return numberAfter;
  }

  public void setList(Vector lst){
   this.lst=lst;

  }


  public List getList(){
    return lst;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cfdf3ca9887e4d9bbdf87be01403e3f4 (do not edit this line) */
