/* Generated By:JJTree: Do not edit this line. ASTRootElements.java */

package eu.fox7.bonxai.bonxai.parser;
import java.util.Vector;


public class ASTRootElements extends SimpleNode {

	private Vector<String> rootElementNames = new Vector<String>();

	public ASTRootElements(int id) {
		super(id);
	}

	public ASTRootElements(bonXaiTree p, int id) {
		super(p, id);
	}

	public void addRoot(String name) {
		this.rootElementNames.add(name);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public Vector<String> getRootElementNames() {
		return this.rootElementNames;
	}
}
