/* Generated By:JJTree: Do not edit this line. ASTSimpleAPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


package eu.fox7.bonxai.bonxai.parser;

public
class ASTSimpleAPattern extends SimpleNode {

  private String name;
  private boolean attribute;
  
  public ASTSimpleAPattern(int id) {
    super(id);
  }

  public ASTSimpleAPattern(bonXaiTree p, int id) {
    super(p, id);
  }


    public void setName(String name){
    this.name = name;
  }
    
  public void setAttribute(boolean attribute) {
	  this.attribute = attribute;
  }


  public String getName(){
    return name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4899f665c01723dba47a6d47aed374ff (do not edit this line) */
