/* Generated By:JJTree: Do not edit this line. ASTUniqueConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package eu.fox7.bonxai.bonxai.parser;

public
class ASTUniqueConstraint extends ASTConstraint {

  public ASTUniqueConstraint(int id) {
    super(id);
  }

  public ASTUniqueConstraint(bonXaiTree p, int id) {
    super(p, id);
  }





  /** Accept the visitor. **/
  public Object jjtAccept(bonXaiTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ab3dc8c451aa17dfd811cfd466aa83b7 (do not edit this line) */
