/* Generated By:JJTree: Do not edit this line. ./bonXaiTreeVisitor.java */

package eu.fox7.bonxai.bonxai.parser;

public interface bonXaiTreeVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTbonXai node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(ASTConstraintBlock node, Object data);
  public Object visit(ASTConstraint node, Object data);
  public Object visit(ASTUniqueConstraint node, Object data);
  public Object visit(ASTKeyConstraint node, Object data);
  public Object visit(ASTKeyRefConstraint node, Object data);
  public Object visit(ASTConstraintSelector node, Object data);
  public Object visit(ASTConstraintFields node, Object data);
  public Object visit(ASTGroupBlock node, Object data);
  public Object visit(ASTGroupRule node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTRootElements node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTAnnotations node, Object data);
  public Object visit(ASTAnnotation node, Object data);
  public Object visit(ASTAnnotationName node, Object data);
  public Object visit(ASTAnnotationValue node, Object data);
  public Object visit(ASTAPattern node, Object data);
  public Object visit(ASTSimpleAPattern node, Object data);
  public Object visit(ASTSimpleAPatternOr node, Object data);
  public Object visit(ASTFullAPattern node, Object data);
  public Object visit(ASTFullAPatternOr node, Object data);
  public Object visit(ASTCPattern node, Object data);
  public Object visit(ASTElementPattern node, Object data);
  public Object visit(ASTMixedRegex node, Object data);
  public Object visit(ASTAll node, Object data);
  public Object visit(ASTRegex node, Object data);
  public Object visit(ASTNamedType node, Object data);
  public Object visit(ASTAttributePattern node, Object data);
  public Object visit(ASTAttributeList node, Object data);
  public Object visit(ASTNameSpaceList node, Object data);
  public Object visit(ASTForeign node, Object data);
  public Object visit(ASTBonxaiType node, Object data);
  public Object visit(ASTAttrBonxaiType node, Object data);
}
