package gjb.util.tree;

/**
 * Class <code>TreeException</code> must be extended by all exceptions
 * that are generated by the <code>gjb.util.tree</code> package.
 *
 * @author <a href="mailto:gjb@luc.ac.be">Geert Jan Bex</a>
 * @version 1.1
 */
public class TreeException extends Exception {

    private static final long serialVersionUID = 1L;

}
