package eu.fox7.jedit.textelement;

public enum Linktype {
  EXPRESSION2TYPE, EXPRESSION2ELEMENT, ELEMENT2EXPRESSION, ELEMENT2TYPE, TYPE2ELEMENT, ELEMENT2BONXAIELEMENT, BONXAIELEMENT2ELEMENT, TYPE2EXPRESSION, XSDELEMENT2ELEMENT, XSDELEMENT2BONXAIELEMENT, ELEMENT2XSDELEMENT, BONXAIELEMENT2XSDELEMENT
}
